# Generated by Django 2.2.4 on 2020-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_and_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='zipcode',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
