# Generated by Django 2.2.4 on 2020-12-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_and_ninjas_app', '0002_dojo_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='zipcode',
        ),
    ]
